version: 0.{build}
image: Ubuntu

services:
- docker

build:
  verbosity: minimal

before_test:
- docker run --network host -d --name clickhouse-server --ulimit nofile=262144:262144 yandex/clickhouse-server
- sleep 10
