version: 0.{build}
image: Ubuntu

environment:
  CLICKHOUSE_CONNECTION: Host=localhost;Port=8123

services:
- docker

build:
  verbosity: minimal

before_test:
- docker run --network host -d --name clickhouse-server --ulimit nofile=262144:262144 yandex/clickhouse-server
- sleep 3
