version: 0.2.0.{build}
image:
  - Visual Studio 2019
  - Ubuntu

environment:
  CLICKHOUSE_CONNECTION: Host=localhost;Port=8123
  NUGET_KEY:
    secure: n3cWbN9kLcg8FjeAiqxg5fBcRqo+s9M6v1cc7ABtMte1ukSDzNgwjds6ztXALQ0w

nuget:
  project_feed: false
  disable_publish_on_pr: true

services:
- docker

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

install:
- cmd: choco install resharper-clt

build_script:
- dotnet build

after_build:
- cmd: InspectCode.exe -o=resharper-clt-output.xml ClickHouse.Client.sln
- ps: $result = [xml](Get-Content .\resharper-clt-output.xml)
- ps: $result.Report.Issues.ChildNodes | ForEach-Object {$project = $_.Name; $_.ChildNodes | ForEach-Object {Add-AppveyorCompilationMessage -Message $_.Message -Line $_.Line -FileName $_.File -ProjectName $project}}

before_test:
- docker pull yandex/clickhouse-server
- docker run -p 8123:8123 -d --name clickhouse-server yandex/clickhouse-server
- sleep 3

test_script:
- dotnet test

artifacts:
- path: '**/*.nupkg'
  name: NuGet

for:
- matrix:
    only:
      - image: Ubuntu
  build_script:
  - dotnet restore
  - msbuild /p:Configuration=Release -verbosity:minimal
